#!/usr/bin/env bash
set -euo pipefail

APP_ENV="${1:-deploy/phala/.env.app}"
REGISTRY_ENV="${2:-deploy/phala/.env.registry}"
OUT_ENV="${3:-deploy/phala/.env.cvm}"

touch "${APP_ENV}" "${REGISTRY_ENV}"

{
  echo "# generated by deploy/phala/merge_cvm_env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# file passed to: phala cvms create --env-file ..."
  echo
  cat "${APP_ENV}"
  echo
  cat "${REGISTRY_ENV}"
} > "${OUT_ENV}"

echo "Wrote ${OUT_ENV}"
